name: AmivTex Docker Image CI

# do this workflow ever month or on push in main
on: push

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into Docker Hub registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_DEV }}
        password: ${{ secrets.DOCKERHUB_TOKEN_DEV }}
    
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME_DEV }}/amivtex:latest
    