name: Docker Image CI

on:
  schedule:
    - cron: '0 0 1 1 *'
  push:
    branches:
      - main
      - setupci
    

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
      # Login against a Docker registry except on PR
    - name: Log into Docker Hub registry
      # if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_TEST_USER }}
        password: ${{ secrets.DOCKERHUB_TEST_TOKEN }}
    
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: nimro/amivtex:latest
