name: AmivTex Docker Image CI

# do this workflow ever month or on push in main
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into Docker Hub registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/amivtex:latest
